name: 'Bikeclub Content type base'
description: 'Provides field storage and text editor formats.'
type: 'Content field'
recipes:
  - core/recipes/feedback_contact_form
  - bikeclub_media
install:
  - ckeditor5
  - contact
  - layout_builder
  - layout_discovery
  - node
  - options
  - taxonomy
  - text
  # Contrib.
  - contact_storage
  - entity_reference_revisions
  - layout_builder_admin_theme
  - layout_builder_restrictions
  - layout_paragraphs
  - linkit
  - paragraphs
  - pathauto
  - quick_node_clone
  - user_contactlink
   #- tac_lite
config:
  strict: false
  import:
    contact_storage: '*'
    linkit: '*'
    node:
      # Import config which is imported by the Standard profile,
      # exclude view_mode.rss, include optional views.
      - core.entity_view_mode.node.full
      - core.entity_view_mode.node.teaser
      - system.action.node_delete_action
      - system.action.node_make_sticky_action
      - system.action.node_make_unsticky_action
      - system.action.node_promote_action
      - system.action.node_publish_action
      - system.action.node_save_action
      - system.action.node_unpromote_action
      - system.action.node_unpublish_action
      - views.view.content
      - views.view.frontpage
    quick_node_clone: '*'    
  # Media is installed so include Media persmissions here.
  actions:
    user.role.anonymous:
      grantPermissions:
        - 'access user contact forms'
    user.role.authenticated:
      grantPermissions:
        - 'access user contact forms'
        - 'use text format basic_html'
        - 'use text format summary_fields'
