name: 'Bikeclub Content type base'
description: 'Provides field storage and text editor formats.'
type: 'Content field'
recipes:
  - core/recipes/feedback_contact_form
  - bikeclub_media
install:
  - ckeditor5
  - contextual
  - editor
  - layout_builder
  - options
  - user
  # Contrib.
  - add_content_by_bundle 
  - conditional_fields  
  - contact_storage
  - entity_reference_revisions
  - field_group
  - layout_builder_admin_theme
  - layout_builder_restrictions
  - layout_paragraphs
  - paragraphs
  - pathauto
  - quick_node_clone
  - scheduler
  - tac_lite
  - token
  - user_contactlink
   #- tac_lite
config:
  strict: false
  import:
    contact_storage: '*'
    pathauto: '*'
    quick_node_clone: '*'
  # Media is installed so include Media persmissions here.
  actions:
    node.settings:
      simpleConfigUpdate:
        use_admin_theme: true
    scheduler.settings:
      simple_config_update:
        allow_date_only: true
        default_time: '01:00:00'
        hide_seconds: true
        log: false
    user.role.anonymous:
      grantPermissions:
        - 'access user contact forms'
    user.role.authenticated:
      grantPermissions:
        - 'access user contact forms'
        - 'use text format basic_html'
        - 'use text format summary_fields'
