name: 'Bikeclub Content type base'
description: 'Provides field storage and text editor formats.'
type: 'Content field'
recipes:
  - core/recipes/feedback_contact_form
  - bikeclub_media
install:
  - ckeditor5
  - layout_builder
  - options
  # Contrib.
  - add_content_by_bundle  
  - contact_storage
  - entity_reference_revisions
  - layout_builder_admin_theme
  - layout_builder_restrictions
  - layout_paragraphs
  - paragraphs
  - pathauto
  - quick_node_clone
  - tac_lite
  - token
  - user_contactlink
   #- tac_lite
config:
  strict: false
  import:
    contact_storage: '*'
    pathauto: '*'
    quick_node_clone: '*'    
  # Media is installed so include Media persmissions here.
  actions:
    node.settings:
      use_admin_theme: true
    user.role.anonymous:
      grantPermissions:
        - 'access user contact forms'
    user.role.authenticated:
      grantPermissions:
        - 'access user contact forms'
        - 'use text format basic_html'
        - 'use text format summary_fields'
    tac_lite:
      simpleConfigUpdate:
        tac_lite_categories:
          page_access: page_access
        tac_lite_schemes: 1
        menu_rebuild_needed: true
        tac_lite_config_scheme_1:
          name: 'View access'
          perms:
            grant_view: grant_view
          unpublished: 0
          term_visibility: 0
        # 1=Admin, 2=Members, 3=Ride leaders. IDs = 1,2,3 depends on default content imported in bikeclub_starter recipe.
        tac_lite_grants_scheme_1:
          anonymous:
            page_access: {  }
          authenticated:
            page_access: {  }
          administrator:
            page_access:
              1: '1'
              2: '2'
              3: '3'
          member:
            page_access:
              2: '2'
          ride_leader:
            page_access:
              3: '3'
          rides_coordinator:
            page_access:
              2: '2'
              3: '3'
          membership:
            page_access:
              2: '2'
              3: '3'
          site_admin:
            page_access:
              1: '1'
              2: '2'
              3: '3'
